### ISSUE TITLE
Is there a way to apply filetype themes persistently or on startup?

### ISSUE THREAD

**Issue by andrewbihl** [vt5491/multi-theme-applicator#9]
As the title says. I'd like to have Atom apply the correct theme to file types without me having to go through the `CMD+Shift+V > Select theme > select scope > Apply` flow every time I open Atom.

**Comment by vt5491** [comment]
Multi-theme-applicator (MTA) should do this automatically.  I call it "sticky themes".  When you first bring up atom, all the buffers (editors) from your prior session will be up, but with the default theme.  Then, when you first invoke MTA via shift-ctrl-v, it should automatically reapply all the themes (by file, by filetype etc) you had applied at the end of your prior session.  

Believe me, I know how much of a pain it was to have to set them up each time, so I added sticky or persistent theming back in v 0.9 on 2016-09-03.   You can see a demo of this feature in the [MTA overview video](https://www.youtube.com/watch?v=7u0TVjH_C4A&t=14s) I made  starting at 19:38.

Note: Sticky themes does not work on window, pane, or editor scoped themes (it only works on file and filetype scopes)

**Comment by andrewbihl** [comment]
I know it's a small detail, but do you know how I could trigger the behavior of shift-ctrl-v (to put the themes in place) as part of the startup script (.atom/init.coffee) for Atom? 

If not, no worries; it would just be cool to have it be fully automatic.

**Comment by vt5491** [comment]
Ok, now I see what you're asking.  I didn't really know off the top of my head, but I googled around a little and found [this link](https://discuss.atom.io/t/autostart-packages/10465/2).  It says that if you edit the package.json for MTA, and remove any entries under 'activationCommands', then the package should start automatically.  

I in fact tried this, and to my amazement it actually worked.  I can't guarantee there won't be any side effects since I haven't thoroughly tested it, but I don't see any particular reason to worry.

Basically, starting from either your '.atom' dir in your home directory, or by typing 'ctrl-,' from atom (settings), drill down to '~/.atom/packages/multi-theme-applicator' and edit package.json.  You'll see something like:

```
   "activationCommands": {
      "atom-workspace": "multi-theme-applicator:toggle"   <-- remove this
    }, 
```
Just delete the line "atom-workspace" (unfortunately, you can't comment out json), and when you cycle atom, MTA will automatically invoke the themes (without even the popup dialog showing to boot).  You don't have to delete the entire 'activationCommands' section, just the entry underneath it.

If this works for you, we'll just have to treat it as a custom per-user one-off for now, as if I make this the default, then it would increase everyone's load time, even if they weren't using MTA.  However, this means that if I ever update MTA, you would probably have to manually re-edit package.json again.   MTA is stable now, so this shouldn't be much of a problem, but I don't see enough demand to make it a permanent feature just yet: but it was an interesting thing to discover, so I thank you for your question.

**Comment by andrewbihl** [comment]
I appreciate you finding this. I gave it a try; it worked right away. If I find any side effects or issues I'll comment here again.

Thanks for your help!

**Comment by andrewbihl** [comment]
UPDATE: This is not working consistently. I have to open the program, select my desired theme, and hit "Apply" on a regular basis. At points in the past, just opening the program would suffice. It's unclear what the exactly is the discrepancy in behavior.
